# Generated by Django 4.2.3 on 2023-12-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncodedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoded_image', models.ImageField(upload_to='encoded_images/')),
                ('decoding_key', models.CharField(max_length=255)),
            ],
        ),
    ]
